rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"

temporal:
  address: "localhost:7233"
  activities:
    num_workers: 10

logs:
  level: debug
  channels:
    temporal:
      level: fatal