version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"

temporal:
  address: "temporal:7233"
  activities:
    num_workers: 4

service:
  interceptors:
    command: "./rr serve -c ./src/Interceptors/.rr.yaml"

logs:
  level: info
  mode: development
